In [1]:
import pandas as pd

In [2]:
data = { \
	'date': ['2023-07-01', '2023-07-01', '2023-07-02', '2023-07-02'], \
	'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'], \
	'temperature': [85, 90, 88, 92], \
	'humidity': [70, 65, 72, 60] \
	}

In [4]:
df = pd.DataFrame(data)
df

         date         city  temperature  humidity
0  2023-07-01     New York           85        70
1  2023-07-01  Los Angeles           90        65
2  2023-07-02     New York           88        72
3  2023-07-02  Los Angeles           92        60

In [6]:
pivoted = df.pivot(index='date', columns='city', values='temperature')
pivoted

city        Los Angeles  New York
date
2023-07-01           90        85
2023-07-02           92        88

In [7]:
pivoted.loc['2023-07-01', 'Los Angeles']

90

In [8]:
# Suppose you want both temperature and humidity 
pivoted_multi = df.pivot(index='date', columns='city')
pivoted_multi

           temperature             humidity
city       Los Angeles New York Los Angeles New York
date
2023-07-01          90       85          65       70
2023-07-02          92       88          60       72

In [9]:
pivoted_multi2 = df.pivot(index='date', columns='city', values=['temperature', 'humidity'])
pivoted_multi2

           temperature             humidity
city       Los Angeles New York Los Angeles New York
date
2023-07-01          90       85          65       70
2023-07-02          92       88          60       72

In [10]:
pivoted_multi['temperature']['New York']

date
2023-07-01    85
2023-07-02    88
Name: New York, dtype: int64

In [12]:
data2 = {
'year': [2023, 2023, 2024, 2024], \
'month': ['Jul', 'Jul', 'Jan', 'Jan'], \
'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'], \
'temperature': [85, 90, 30, 65] \
}
df2 = pd.DataFrame(data2)
df2

   year month         city  temperature
0  2023   Jul     New York           85
1  2023   Jul  Los Angeles           90
2  2024   Jan     New York           30
3  2024   Jan  Los Angeles           65

In [13]:
pivoted2 = df2.pivot(index=['year', 'month'], columns='city', values='temperature')
pivoted2

city        Los Angeles  New York
year month
2023 Jul             90        85
2024 Jan             65        30

In [14]:
pivoted3 = df.pivot(index='date', columns='city') 
pivoted3

           temperature             humidity
city       Los Angeles New York Los Angeles New York
date
2023-07-01          90       85          65       70
2023-07-02          92       88          60       72

In [15]:
pivoted = df.pivot_table(index='date', columns='city', values='temperature', aggfunc='mean')
pivoted

city        Los Angeles  New York
date
2023-07-01         90.0      85.0
2023-07-02         92.0      88.0